---
title: "importar_fevereiro"
author: "BML"
date: "2024-08-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
```

```{r}
read_tab <- function(x) {read_delim(x, 
    delim = "\t", escape_double = FALSE, 
    locale = locale(decimal_mark = ",", grouping_mark = "."), 
    trim_ws = TRUE)}
```


```{r include=FALSE}
source(knitr::purl("tabelas_versao_atual.Rmd", quiet=TRUE))
```

# Preparar arquivos

```{r}
arquivos_fev_2024 <- list.files(path = "csv", pattern = "tsv")

```

```{r}
i <- 1
for(i in seq_along(arquivos_fev_2024)){
  arquivos_fev_2024[i] <- paste0("csv/", arquivos_fev_2024[i])
  i <- i + 1
}
arquivos_fev_2024

# read_tab(arquivos_fev_2024[1])
```
# Criar lista com arquivos de fevereiro de 2024
```{r include=FALSE}
lista_tabelas_fev <- map(arquivos_fev_2024, read_tab)
```
```{r}
lista_tabelas_fev. <- lista_tabelas_fev
```

## Limpando arquivos
Unindo tabelas que foram publicadas separadamente
```{r}

names(lista_tabelas_fev[[8]]) <- names(lista_tabelas_fev[[7]]) 

lista_tabelas_fev[[7]] <- rbind(lista_tabelas_fev[[7]], lista_tabelas_fev[[8]])

lista_tabelas_fev[[9]] <- rbind(lista_tabelas_fev[[9]], lista_tabelas_fev[[10]])



```

```{r}
lista_tabelas_fev[[8]] <- NULL

lista_tabelas_fev[[9]] <- NULL

```

```{r}
lista_tabelas_fev
```

# Unir arquivos de fevereiros com anteriores

O conteúdo dos dataframes 1, 2 e 4 (tabelas com históricos) já está incorporado.

```{r}
lista_tabelas_fev[1]
lista_tabelas_fev[2]
lista_tabelas_fev[4]
```

```{r}
tail(Historico_petroleo)
tail(Historico_prod_gas)
tail(Historico_de_Producao_de_Petroleo_Gas_Natural)
```


