---
title: "Extrair dados worksheet 5"
output: html_document
date: "2024-06-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(plyr)
library(tidyverse)
library(readxl)
library(qpcR)
library(janitor)

```


```{r}
# todas as planilhas e as planilhas com WS 5
planilhas <- dir(path = "data", pattern = "*xls*")

planilhas_ws5 <- planilhas[c(32:39, 51)]


extrair_dados_ws5 <- function(num_planilha){


# importando planilha completa
ws5_1_prov <- read_excel(paste0("data/", planilhas_ws5[num_planilha]), sheet = 5)



# Filtrando a primeira coluna e criando colunas auxiliares
names(ws5_1_prov)[1] <- "col1"
 
ws5_1_prov <- ws5_1_prov |> 
  mutate(num_linhas = 1:nrow(ws5_1_prov)) |> 
  mutate(linha_inicial = str_detect(col1, "Tabela")) |>
  mutate(em_branco = is.na(col1),
         linha_final = em_branco + lag(em_branco) + lag(em_branco, 2)) 

       

# Criando tabelas com os pontos fixados

linha_inicial <- ws5_1_prov |> 
  filter(linha_inicial == TRUE) |> 
  pull(num_linhas)
  
linha_final <- ws5_1_prov |> 
  filter(linha_final > 2) |> 
  pull(num_linhas)

pontos_de_corte <- data.frame(linha_inicial = linha_inicial,
                              linha_final = linha_final)



df1 <- read_excel(paste0("data/", planilhas_ws5[1]), sheet = 5, range = cell_rows(pontos_de_corte$linha_inicial[1]+7: pontos_de_corte$linha_final[1]-4)) 


# df1 <- read_excel(paste0("data/", planilhas_ws5[1]), sheet = 5, skip = pontos_de_corte$linha_inicial[2])

df2 <- read_excel(paste0("data/", planilhas_ws5[1]), sheet = 5, skip = linha_inicial[2])

saida <- list(df1, df2)

}
```


```{r}
ws6_1 <- extrair_dados_ws5(1)

ws6_2 <- extrair_dados_ws5(2)

ws6_3 <- extrair_dados_ws5(3)

ws6_4 <- extrair_dados_ws5(4)

ws6_5 <- extrair_dados_ws5(5)

ws6_6 <- extrair_dados_ws5(6)

ws6_7 <- extrair_dados_ws5(7)

ws6_8 <- extrair_dados_ws5(8)

ws6_9 <- extrair_dados_ws5(9)


```
```{r}
ws6_1
ws6_2
ws6_3
ws6_4
ws6_5
ws6_6
ws6_7
ws6_8
ws6_9
```

```{r}
ws6_1[[2]] |> head()
ws6_2[[2]] |> head()
ws6_3[[2]] |> head()
ws6_4[[2]] |> head()

names(ws6_1[[2]]) <- "col1"
names(ws6_2[[2]]) <- "col1"
names(ws6_3[[2]]) <- "col1"

# precisam de correção

ws6_1[[2]] <- ws6_1[[2]] |>  
  clean_names() |> 
  filter(!is.na(col1)) |> 
  janitor::row_to_names(1)

ws6_2[[2]] <- ws6_2[[2]] |>  
  clean_names() |> 
  filter(!is.na(col1)) |> 
  janitor::row_to_names(1)

ws6_3[[2]] <- ws6_3[[2]] |>  
  clean_names() |> 
  filter(!is.na(col1)) |> 
  janitor::row_to_names(1)

ws6_1[[2]] |> head()
ws6_2[[2]] |> head()
ws6_3[[2]] |> head()
ws6_4[[2]] |> head()
```


```{r}
ws6_1[[1]] |> tail(8)
ws6_2[[1]]|> tail(8)
ws6_3[[1]]|> tail(8)
ws6_4[[1]]|> tail(8)
ws6_5[[1]]|> tail(8)
ws6_6[[1]]|> tail(8)
ws6_7[[1]]|> tail(8)
ws6_8[[1]]|> tail(8)
ws6_9[[1]]|> tail(8)
```


```{r}
Tabela20 <- 
bind_rows(ws6_1[[1]],
ws6_2[[1]],
ws6_3[[1]],
ws6_4[[1]],
ws6_5[[1]],
ws6_6[[1]],
ws6_7[[1]],
ws6_8[[1]],
ws6_9[[1]]
) 

Tabela20
```
```{r}
Tabela21 <- 
bind_rows(#ws6_1[[2]],
#ws6_2[[2]],
#ws6_3[[2]],
ws6_4[[2]],
ws6_5[[2]],
ws6_6[[2]],
ws6_7[[2]],
ws6_8[[2]],
ws6_9[[2]]
) 

Tabela21_char <- bind_rows(ws6_1[[2]],
ws6_2[[2]],
ws6_3[[2]]
) 
  

Tabela21
```

```{r}
resumo_ws5
```
```{r}
planilhas_ws5 <- planilhas[arquivos_covid]

importacao_ws5 <- map_df(planilhas_ws5, read_excel_data, sheet = 5)

inicio_df1 <- importacao_ws5 |> 
  mutate(num_linhas = 1:nrow(importacao_ws5)) |> 
  filter(str_detect(...1, "Tabela 19. Campos|Tabela 20. Campos") ) |> 
  pull(num_linhas)

inicio_df2 <- importacao_ws5 |> 
  mutate(num_linhas = 1:nrow(importacao_ws5)) |> 
  filter(str_detect(...1, "Tabela 20. Plataformas|Tabela 21. Plataformas") ) |> 
  pull(num_linhas)

```

```{r}
read_excel_data()
```

```{r}




```
```{r}
planilhas_ws5. <- planilhas_ws5 |> 
  mutate(num_linhas = 1:nrow(planilhas_ws5)) |> 
  filter(str_detect(...1, "Tabela") ) |> 
  clean_names() 

planilhas_ws5.[,1] |> 
  distinct()


```

