---
title: "Extrair dados worksheet 3"
output: html_document
date: "2024-06-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(janitor)
library(xml2)
library(XML)
library(clock)
```
```{r}
planilhas <- dir(path = "data", pattern = "*xls*")
planilhas_ws3_grupo1 <- planilhas[1:3]
planilhas_ws3_grupo2 <- planilhas[4:32]
planilhas_ws3_grupo3 <- planilhas[33:57]
planilhas_ws3_grupo4 <- planilhas[58:77]

planilhas_ws3 <- c(planilhas_ws3_grupo1,  planilhas_ws3_grupo2,  planilhas_ws3_grupo3, planilhas_ws3_grupo4)
```



Função para extrair a data da planilha

```{r}
planilhas_ws3_zip <- planilhas_ws3

planilhas_ws3_zip <- planilhas_ws3_zip |> 
  str_replace_all(pattern = "xlsm", replacement = "zip")

extrair_data_ws3 <- function(num){
  
invisible(file.copy(from = paste0("data/", planilhas_ws3[num]), to = paste0("data/zip/", planilhas_ws5_zip[num]), overwrite = TRUE))

unzip(zipfile = paste0("data/zip/", planilhas_ws3_zip[num]), exdir = "data/zip", overwrite = TRUE)

xml_prov <- xmlParse("data/zip/xl/drawings/drawing1.xml") |> 
  xmlToDataFrame()

sheet1_data <- xml_prov[2,3] |> 
  str_remove_all("/.*") |> 
    str_trim() |> 
  str_remove_all("[:punct:]") |> 
  str_remove_all(" de")

mes_boletim <- paste0("01 ",sheet1_data) |> 
      clock::date_parse(format = "%d %B %Y",
      locale = clock_locale("pt"))

mes_boletim 

}
```

```{r message=FALSE, warning=FALSE}
data_planilha <- extrair_data_ws3(1)
```

```{r}
prov1 <- read_excel(paste0("data/", planilhas_ws3[1]), sheet = 3)

names(prov1)[1] <- "col1"

corte <- which(str_detect(prov1$col1, "Tabela [0-9]"))

corte
```
```{r}
prov1[38,1]
```


Criando uma função para extrair os dados

```{r}

extrair_dados_ws3 <- function(num, ajuste = 2, sheet = 3){

data_planilha <- extrair_data_ws3(num)

prov1 <- read_excel(paste0("data/", planilhas_ws3[num]), sheet = sheet)

names(prov1)[1] <- "col1"

corte <- which(str_detect(prov1$col1, "Tabela [0-9]*"))


df1 <- read_excel(paste0("data/", planilhas_ws3[num]), sheet = sheet, skip = corte[1] + ajuste, n_max = corte[1 + 1] - corte[1]) |> 
  mutate(data = data_planilha) 

df2 <- read_excel(paste0("data/", planilhas_ws3[num]), sheet = sheet, skip = corte[1 + 1] + ajuste, n_max = corte[1 + 2] - corte[1 + 1]) |> 
  mutate(data = data_planilha)
  sheet
df3 <- read_excel(paste0("data/", planilhas_ws3[num]), sheet = sheet, skip = corte[1 + 2] + ajuste, n_max = corte[1 + 3] - corte[1 + 2]) |> 
  mutate(data = data_planilha)
  
df4 <- read_excel(paste0("data/", planilhas_ws3[num]), sheet = sheet, skip = corte[1 + 3] + ajuste, n_max = corte[1 + 4] - corte[1 + 3]) |> 
  mutate(data = data_planilha)  
  
df5 <- read_excel(paste0("data/", planilhas_ws3[num]), sheet = sheet, skip = corte[1 + 4] + ajuste, n_max = corte[1 + 5] - corte[1 + 4]) |> 
  mutate(data = data_planilha)    
  
df6 <- read_excel(paste0("data/", planilhas_ws3[num]), sheet = sheet, skip = corte[1 + 5] + ajuste, n_max = corte[1 + 6] - corte[1 + 5]) |> 
  mutate(data = data_planilha)

df7 <- read_excel(paste0("data/", planilhas_ws3[num]), sheet = sheet, skip = corte[1 + 6] + ajuste, n_max = corte[1 + 7] - corte[1 + 6]) |> 
  mutate(data = data_planilha)

df8 <- read_excel(paste0("data/", planilhas_ws3[num]), sheet = sheet, skip = corte[1 + 7] + ajuste, n_max = corte[1 + 8] - corte[1 + 7]) |> 
  mutate(data = data_planilha)

df9 <- read_excel(paste0("data/", planilhas_ws3[num]), sheet = sheet, skip = corte[1 + 8] + ajuste, n_max = corte[1 + 9] - corte[1 + 8]) |> 
  mutate(data = data_planilha)
  
df10 <-  read_excel(paste0("data/", planilhas_ws3[1]), sheet = sheet, skip = corte[1+9] + ajuste) |> 
  mutate(data = data_planilha)






list(df1, df2, df3, df4, df5, df6, df7, df8, df9, df10)

}

```



```{r message=FALSE, warning=FALSE}
assign(paste0("ws3", 1),  extrair_dados_ws3(num = 1, ajuste = 2, sheet = 3))

ws31
```


```{r message=FALSE, warning=FALSE}

i <= 1
while (i < length(planilhas_ws5) + 1) {
assign(paste0("nome", i),  extrair_dados_ws5(num = 1, ajuste = 2))  
  i <- i + 1
}

```

```{r}
nome1
nome2
nome3
nome4
nome5
nome6
nome7
nome8
nome9
```



Demonstração: extraindo dados da planilha 1
```{r}
prov1 <- read_excel(paste0("data/", planilhas_ws5[1]), sheet = 5)

names(prov1)[1] <- "col1"

corte <- which(str_detect(prov1$col1, "Tabela [0-9]"))


df1 <- read_excel(paste0("data/", planilhas_ws5[1]), sheet = 5, skip = corte[1] + 2, n_max = corte[1 + 1]) |> 
  mutate(data = data_planilha)
         
df2 <- read_excel(paste0("data/", planilhas_ws5[1]), sheet = 5, skip = corte[2] + 2) |> 
  mutate(data = data_planilha)
  
list(df1, df2)
```

